#!/usr/bin/env bash
#
# baseline-profile.sh — Capture a startup + memory + response-time snapshot.
#
# Fills the gaps left by scripts/performance-test.ts (#603):
#   - cold-start time to "Engine initialized"
#   - memory at idle (RSS via pm2)
#   - response-time samples for a few representative routes
#
# Usage:
#   scripts/baseline-profile.sh                    # measure current install
#   scripts/baseline-profile.sh --cold-start       # also stop/start the server
#
# Output:
#   docs/performance/baseline-<version>-<date>.md
#
# Requirements: ./server.sh, jq, gh, curl, pm2 available via npx.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

VERSION=$(node -p "require('./package.json').version")
TODAY=$(date +%Y-%m-%d)
OUT_DIR="$REPO_ROOT/docs/performance"
OUT_FILE="$OUT_DIR/baseline-v${VERSION}-${TODAY}.md"
mkdir -p "$OUT_DIR"

PORT=$(grep -E '^PORT=' .env 2>/dev/null | head -1 | cut -d= -f2 || echo "3000")
BASE_URL="http://localhost:${PORT}"

INSTANCE_NAME=$(npx pm2 jlist 2>/dev/null \
  | jq -r --arg port "$PORT" '.[] | select(.pm2_env.PORT == $port or (.pm2_env.env.PORT // "") == $port) | .name' \
  | head -1)
INSTANCE_NAME="${INSTANCE_NAME:-jimstest}"

echo "Repo:      $REPO_ROOT"
echo "Version:   v${VERSION}"
echo "Instance:  $INSTANCE_NAME (port $PORT)"
echo "Output:    $OUT_FILE"
echo

# ── Cold-start timing (optional) ──────────────────────────────────────────────

COLD_START_MS=""
LINK_GRAPH_MS=""
LINK_GRAPH_ENTRIES=""

if [[ "${1:-}" == "--cold-start" ]]; then
  echo "→ Measuring cold start (./server.sh stop && start)…"
  ./server.sh stop >/dev/null 2>&1 || true
  sleep 2
  START_TS=$(date +%s%3N)
  ./server.sh start >/dev/null 2>&1 || true
  # Wait for the engine-ready marker
  for _ in {1..60}; do
    if grep -q '✅ ngdpbase Engine initialized successfully' "${FAST_STORAGE:-./data}/logs/pm2-out.log" 2>/dev/null; then
      break
    fi
    sleep 1
  done
  END_TS=$(date +%s%3N)
  COLD_START_MS=$((END_TS - START_TS))
  echo "  cold-start: ${COLD_START_MS} ms"
fi

# Always look back for the most recent link-graph entry-count + duration.
PM2_OUT="${FAST_STORAGE:-./data}/logs/pm2-out.log"
if [[ -f "$PM2_OUT" ]]; then
  LINK_GRAPH_LINE=$(grep 'Link graph built with' "$PM2_OUT" | tail -1)
  if [[ -n "$LINK_GRAPH_LINE" ]]; then
    LINK_GRAPH_ENTRIES=$(echo "$LINK_GRAPH_LINE" | grep -oE '[0-9]+ entries' | grep -oE '[0-9]+')
  fi
fi

# ── Memory snapshot via pm2 ───────────────────────────────────────────────────

MEM_BYTES=$(npx pm2 jlist 2>/dev/null \
  | jq -r --arg name "$INSTANCE_NAME" '.[] | select(.name == $name) | .monit.memory' \
  | head -1)
MEM_MB=$(awk -v b="${MEM_BYTES:-0}" 'BEGIN { printf "%.1f", b / 1024 / 1024 }')
PAGE_COUNT=$(find data/pages -name '*.md' 2>/dev/null | wc -l | tr -d ' ')

echo "→ Memory snapshot: ${MEM_MB} MB resident"
echo "→ Pages on disk:   ${PAGE_COUNT}"

# ── Response-time samples ─────────────────────────────────────────────────────

echo "→ Sampling response times (10 iterations per route)…"

# Parallel arrays — macOS bash 3.2 has no associative arrays.
# Routes are chosen for unauthenticated access. /edit/* and admin routes are
# excluded because they 302 to /login; their timings would reflect login page
# render, not the actual feature.
ROUTES=("/" "/view/Welcome" "/search?q=test" "/login")
ROUTE_TIMES=()
for route in "${ROUTES[@]}"; do
  total=0
  samples=0
  for _ in {1..10}; do
    ms=$(curl -sSL -o /dev/null -w '%{time_total}' --max-time 10 "${BASE_URL}${route}" 2>/dev/null \
      | awk '{ printf "%d", $1 * 1000 }')
    if [[ -n "$ms" ]]; then
      total=$((total + ms))
      samples=$((samples + 1))
    fi
  done
  if [[ "$samples" -gt 0 ]]; then
    ROUTE_TIMES+=("$((total / samples))")
  else
    ROUTE_TIMES+=("-")
  fi
done

# ── Write the markdown report ─────────────────────────────────────────────────

{
  echo "# Performance baseline — v${VERSION}"
  echo
  echo "Captured ${TODAY} on instance \`${INSTANCE_NAME}\` (port ${PORT})."
  echo
  echo "## Snapshot"
  echo
  echo "| Metric | Value |"
  echo "| --- | --- |"
  echo "| Version | v${VERSION} |"
  echo "| Pages on disk | ${PAGE_COUNT} |"
  echo "| Resident memory (idle) | ${MEM_MB} MB |"
  if [[ -n "$LINK_GRAPH_ENTRIES" ]]; then
    echo "| Link-graph entries | ${LINK_GRAPH_ENTRIES} |"
  fi
  if [[ -n "$COLD_START_MS" ]]; then
    echo "| Cold-start time (./server.sh start → Engine initialized) | ${COLD_START_MS} ms |"
  fi
  echo
  echo "## Response times (mean across 10 samples)"
  echo
  echo "| Route | Time |"
  echo "| --- | --- |"
  for i in "${!ROUTES[@]}"; do
    echo "| \`${ROUTES[$i]}\` | ${ROUTE_TIMES[$i]} ms |"
  done
  echo
  echo "## Methodology"
  echo
  echo "Generated by \`scripts/baseline-profile.sh\`. Memory read from \`pm2 jlist\` for the running instance. Response times measured with \`curl -L --time_total\` (follows redirects) against a warm server, 10 iterations per route, mean reported. Routes chosen are unauthenticated — \`/edit/*\` and admin routes redirect to \`/login\`, so their timings would not reflect the actual feature. Cold-start time measured only when invoked with \`--cold-start\` — wraps \`./server.sh stop\` + \`./server.sh start\` and waits for the \"Engine initialized\" marker in \`pm2-out.log\`."
  echo
  echo "Re-run on each release to track drift over time. Compare against the previous baseline file in \`docs/performance/\` to spot regressions."
} > "$OUT_FILE"

echo
echo "✅ Baseline written to: $OUT_FILE"
